/*
  * Project version information. Generated - do not modify.
  */
 package mondrian.server;
 /**
  * Version information for Mondrian. (Generated by build)
  */
 class MondrianServerVersion {
     static final String VENDOR = "Pentaho";
     static final String NAME = "mondrian";
     static final String VERSION = "3.5.6";
     static final int MAJOR_VERSION = 3;
     static final int MINOR_VERSION = 56;
 }

 // End MondrianServerVersion.java